### ISSUE TITLE
간헐적으로 아래와 같은 오류가 발생합니다.

### ISSUE THREAD

**Issue by mishka86** [Shin-JaeHeon/vue-naver-maps#14]
Error in callback for watcher "lat": "TypeError: Cannot read property 'setPosition' of null"

타이밍 이슈 같은데 해결방법을 모르겠네요 ㅠㅜ
데이터를 비동기로 불러와서 사용하는데
지도가 데이터 보다 먼저 그려져서 생기는 문제 같습니다.
데이터 이후에 지도가 다시 그려지거나 데이터 불러오는 동안 지도 그려지는걸 멈추는 방법이 있을까요?

**Comment by Shin-JaeHeon** [comment]
추후 옵션으로 수동으로 로딩을 할 수 있도록 하겠습니다.

해당 기능 출시 전까지는 기본값으로 숫자를 사용하여주시면 오류가 해결되리라 생각됩니다.

**Comment by mishka86** [comment]
기본값을 숫자로 해놓은 상태입니다 ㅠㅜ
기본값을 숫자로 해놓아도 같은 오류가 발생합니다. 오류는 발생하는데 지도는 그려집니다.
오류가 발생하지 않으면 지도가 정상적으로 노출되지 않습니다. 정상적인 상황인가요??

**Comment by Shin-JaeHeon** [comment]
@mishka86 
오류 메시지 전체 및 마커를 사용하시는 부분의 코드를 캡처해주세요.
사용버전은 최신 버전이신가요?
