### ISSUE TITLE
라우터로 페이지 이동시 마커가 사라집니다.

### ISSUE THREAD

**Issue by siz0001** [Shin-JaeHeon/vue-naver-maps#19]
처음 페이지 로딩시 마커가 뜨고,
![image](https://user-images.githubusercontent.com/42665078/77251621-b8d1be80-6c92-11ea-8a2a-b81ebda65bd0.png)

다른 페이지로 라우터 이동후 다시 돌아오면 마커가 사라져버립니다.
![image](https://user-images.githubusercontent.com/42665078/77251628-c4bd8080-6c92-11ea-9a2a-d83282e4adcf.png)

새로고침을 하면 다시 보이는데 이게 왜이런건지 잘 모르겠어요.

**Comment by siz0001** [comment]
`<template>
  <v-component>
    <naver-maps :height="400" :map-options="mapOptions" @load="onLoad">
      <naver-info-window
        class="info-window"
        :is-open="true"
        :marker="markers"
        @load="onWindowLoad"
      >        
      </naver-info-window>
      <naver-marker
        :lat="mapOptions.lat"
        :lng="mapOptions.lng"
        @load="onMarkerLoaded"
      />      
      <naver-marker v-for="(item,i) in markers" :key="i" :lat="item.lat" :lng="item.lng" @click="onMarkerClicked" @load="onMarkerLoaded"></naver-marker>
    </naver-maps>
  </v-component>
</template>
<script>
export default {
  data: () => ({
    marker: null,
    markers: [
      {
        lat: 37.1,
        lng: 127.1
      },
      {
        lat: 37.2,
        lng: 127.2
      }

    ]
    ,
    mapOptions: {
      lat: 37.530723,
      lng: 126.64875,
      zoom: 9,
      zoomControl: true,
      zoomControlOptions: { position: 'TOP_RIGHT' },
      mapTypeControl: true
    }
  }),
  mounted(){
     this.onMarkerLoaded() 
  },
  methods: {
    // naver-marker는 다음과 같은 체이닝이 가능합니다.
    
    onLoad(_map) {
      this.map = _map
      navigator.geolocation.getCurrentPosition(_position => {
        this.map.setCenter(
          _position.coords.latitude,
          _position.coords.longitude,          
        )
        this.mapOptions.lat = _position.coords.latitude
        this.mapOptions.lng = _position.coords.longitude
      })
    },
      onMarkerLoaded(vue) {
      vue.marker
        .setDraggable(false)
        .setCursor('')
        .setClickable(true)
    },

    onMarkerClicked(event) {
      console.log(event) // 네이버 event 객체
    }
  }
}
</script>`

**Comment by siz0001** [comment]
> <template>
  <v-component>
    <naver-maps :height="400" :map-options="mapOptions" @load="onLoad">
      <naver-info-window
        class="info-window"
        :is-open="true"
        :marker="markers"
        @load="onWindowLoad"
      >        
      </naver-info-window>
      <naver-marker
        :lat="mapOptions.lat"
        :lng="mapOptions.lng"
        @load="onMarkerLoaded"
      />      
      <naver-marker v-for="(item,i) in markers" :key="i" :lat="item.lat" :lng="item.lng" @click="onMarkerClicked" @load="onMarkerLoaded"></naver-marker>
    </naver-maps>
  </v-component>
</template>
<script>
export default {
  data: () => ({
    marker: null,
    markers: [
      {
        lat: 37.1,
        lng: 127.1
      },
      {
        lat: 37.2,
        lng: 127.2
      }

    ]
    ,
    mapOptions: {
      lat: 37.530723,
      lng: 126.64875,
      zoom: 9,
      zoomControl: true,
      zoomControlOptions: { position: 'TOP_RIGHT' },
      mapTypeControl: true
    }
  }),
  mounted(){
     this.onMarkerLoaded() 
  },
  methods: {
    // naver-marker는 다음과 같은 체이닝이 가능합니다.
    
    onLoad(_map) {
      this.map = _map
      navigator.geolocation.getCurrentPosition(_position => {
        this.map.setCenter(
          _position.coords.latitude,
          _position.coords.longitude,          
        )
        this.mapOptions.lat = _position.coords.latitude
        this.mapOptions.lng = _position.coords.longitude
      })
    },
      onMarkerLoaded(vue) {
      vue.marker
        .setDraggable(false)
        .setCursor('')
        .setClickable(true)
    },

    onMarkerClicked(event) {
      console.log(event) // 네이버 event 객체
    }
  }
}
</script>

**Comment by Shin-JaeHeon** [comment]
안녕하세요.

이슈 확인하였습니다. 

감사합니다.

**Comment by Shin-JaeHeon** [comment]
이슈 해결 방법을 찾을 때 까지 임시적으로 페이지를 새로 고치는 방법을 사용하셔야 할듯합니다.

**Comment by Shin-JaeHeon** [comment]
0.12.1버전을 배포하였습니다.
