### ISSUE TITLE
마커이미지, InfoWindow문의 드립니다.

### ISSUE THREAD

**Issue by dhdydtkd9101** [Shin-JaeHeon/vue-naver-maps#24]
**마커이미지**
        this.maker_List[this.Maker_Count]= vue.marker;
        this.maker_List[this.Maker_Count].setTitle(this.Maker_Count);
        this.tableSelect[this.Maker_Count]=0;
        //this.maker_List[this.Maker_Count].setIcon("http://static.naver.com/maps2/icons/pin_spot3.png");
        this.maker_List[this.Maker_Count].setIcon("@/assets/images/taxi.png");
주석처리된 네이버에서 지원하는 마커이미지 Icon은 잘 됩니다.
현재 사용하고싶은 이미지가 있는데 이런식의 로컬에서 가지고와서 적용하는건 안되는지 
만약 된다면 저기 코드가 왜 안되는지 알려주시면 감사하겠습니다.

**InfoWindow**
this.map_infoWindow.setPosition(this.marker_select.getPosition());
현재 InfoWindow 는 n.LatLng의 값으로만 위치를 변경할수 있습니다.
그 이외의 값은 최소 한번만 처리 되고 그 후 처리가 안됩니다. (마커 2개를 가지고 InfoWindow를 움직이시면 에러상황 나올꺼라고 생각합니다.)
처음 마커를 생성할때 
<naver-marker :lat=templat :lng=templng
        @click="ListMarkerClicked(index)" @load="TempMarkerLoaded" ></naver-marker>
이런식의 코드가 되는데 여기서 생성방법이 n.LatLng값으로 셋팅됩니다.

**전체 코드**
전체 코드 메일 적어주시면 보내드리겠습니다.

**Comment by Shin-JaeHeon** [comment]
안녕하새요.

vue-naver-maps에서, 동작이 안되는 경우가 있을 경우에는, 각 컴포넌트의 map 객체를 활용하여(`@onload` 이벤트 참조바랍니다.) 직접 set 해주시기 바랍니다.

감사합니다.

**Comment by Shin-JaeHeon** [comment]
안녕하세요.

1. 안녕하세요. setIcon은 naver.maps.Marker 객체의 setIcon을 사용하는 것이기 때문에, `import * as from '@/assets/images/taxi.png';` 와 같은 코드를 시도해보세요.

2. 최근에 배포된 0.14.0 버전에서, InfoWindow의 경우 moreOptions 객체를 사용할 수 있게 변경되었습니다.

ps. vue-naver-maps에서, 동작이 안되는 경우가 있을 경우에는, 각 컴포넌트의 map 객체를 활용하여(`@onload` 이벤트 참조바랍니다.) 직접 set 해주시기 바랍니다.

감사합니다.
