### ISSUE TITLE
naver-info-window 문의 드립니다.

### ISSUE THREAD

**Issue by Whoing** [Shin-JaeHeon/vue-naver-maps#27]
```
<template>
  <div>
    <naver-maps
      :width="map_width"
      :height="map_height"
      :mapOptions="mapOptions"
      :initLayers="initLayers"
      @load="onLoad"
    >
      <naver-info-window
        class="info-window"
        :isOpen="isOpen"
        :marker="marker"
        @load="onInfoLoad"
      >
        <div class="info-window-container">
          <h3>{{ info_msg }}</h3>
        </div>
      </naver-info-window>
      <div v-for="mark in marker_coords" :key="mark.index">
        <naver-marker
          :lat="mark.lat"
          :lng="mark.lng"
          @click="onMarkerClicked(mark.index)"
          @load="onMarkerLoad"
        />
      </div>
    </naver-maps>
  </div>
</template>
<script>
```
위 소스에서 마커를 클릭 시 해당 이벤트 isOpen = true 로 변경되는 것은 확인 되었으나 
naver-info-window  창이 뜨지 않습니다.
마커의 이벤트는 동작하는것으로 보아 naver-info-window (InfoWindow.vue) 의 이벤트가 나타나지 않는것 같습니다.
문서 상의 예제 소스로도 실행해본 결과 마커 클릭 시 창이 뜨지않습니다.

전체 코드
전체 코드 메일 적어주시면 보내드리겠습니다.

**Comment by Whoing** [comment]
`<template>
  <div>
    <naver-maps
      :width="map_width"
      :height="map_height"
      :mapOptions="mapOptions"
      :initLayers="initLayers"
      @load="onLoad"
    >
      <naver-info-window
        class="info-window"
        :isOpen="isOpen"
        :marker="marker"
        @load="onInfoLoad"
      >
        <div class="info-window-container">
          <h3>{{ info_msg }}</h3>
        </div>
      </naver-info-window>
      <div v-for="mark in marker_coords" :key="mark.index">
        <naver-marker
          :lat="mark.lat"
          :lng="mark.lng"
          @click="onMarkerClicked(mark.index)"
          @load="onMarkerLoad"
        />
      </div>
    </naver-maps>
  </div>
</template>
<script>`

**Comment by Whoing** [comment]
[추가] 
package.json 을 0.13.1로 낮추고 재빌드 한 결과 정상적으로 작동합니다.
naver-info-window 의 1.14.0 option 선택 예제가 있을까요?? 
0.14.0 에서는 여전히 에러를 출력하고 있어서요 ㅠ

**Comment by Shin-JaeHeon** [comment]
@Whoing 

이슈 확인하였습니다.

**Comment by Shin-JaeHeon** [comment]
@Whoing 

`0.14.1` 버전으로 업그레이드 하시면 해결됩니다. 

감사합니다.

**Comment by Whoing** [comment]
넵 감사합니다~
