### ISSUE TITLE
naver.maps.Map의 init 이벤트 관련

### ISSUE THREAD

**Issue by megatiger** [Shin-JaeHeon/vue-naver-maps#40]
안녕하세요.
좋은 모듈을 배포해주셔서 감사합니다.

naver-map 컴포넌트에 naver.maps.Map에 정의된 다른 이벤트들을 호출하면 동작이 잘 됐는데
init 이벤트는 응답이 없어서 소스를 보니 Map.vue 파일에 init 이벤트 대신 init_stylemap 이벤트가 등록되어있는 것으로 보입니다.
아마 언젠가 이벤트명이 변경됐을 것으로 예상되는데요,
확인 부탁드립니다.

**Comment by Shin-JaeHeon** [comment]
0.14.4에서 해결되었습니다. 
close #40
