### ISSUE TITLE
[Bug] Webpack 4 -> 5

### ISSUE THREAD

**Issue by devhun** [Shin-JaeHeon/vue-naver-maps#49]
저희 프로젝트에서는 WEBPACK 4 를 사용중인데, 이번 0.14.4 업데이트 인 webpack 버전이 업그레이드 되며 오류가 발생하고 있습니다.
vue-naver-maps 를 0.14.3 으로 강제설치 하게하여 오류는 해결 했습니다만 webpack 버전의 경우 patch 버전이 아닌 minor 또는 major 버전의 증가가 되야 하지 않을까 싶습니다.

**Comment by Shin-JaeHeon** [comment]
@devhun 
안녕하세요.
정확히 어떤 문제가 발생하고 있는지 알려주셔야 문제 해결에 도움을 드릴 수 있습니다. 
오류문구 캡쳐 등을 부탁드리겠습니다.

감사합니다.

**Comment by devhun** [comment]
@Shin-JaeHeon 
여행을 나와있어서 다음주중에 현상 재현하여 스크린샷 등을 올려보도록 하겠습니다

**Comment by devhun** [comment]
@Shin-JaeHeon 

0.14.3 버전으로 설치해서 사용할 경우 오류가 없으나 0.14.4 버전으로 설치가 될 경우 아래 첨부한 스크린샷 같이 오류가 발생하여 웹페이지 로드가 되지 않습니다.

vue: 2.6.11 버전 사용중입니다.
vue-cli 를 사용하여 설치 하여 사용하고 있습니다.

<img width="1712" alt="스크린샷 2023-03-20 오전 9 56 04" src="https://user-images.githubusercontent.com/7991383/226222750-913680f2-5093-487c-807a-bbb2932fcccb.png">

**Comment by jjangga0214** [comment]
해결하는 PR 드렸습니다. 

> 웹팩 5 가 nodejs polyfill 을 자동삽입하던 것을 제거하긴 하였으나
 
이 문제가 맞네요. 다만 이 패키지가 잘못된 것이 아니라 사용하시는 프로젝트에서 설정을 잘못 하신것 아닌가 생각했었는데, 해당 패키지의 오류가 맞습니다.

> webpack 버전의 경우 patch 버전이 아닌 minor 또는 major 버전의 증가가 되야 하지 않을까 싶습니다.

하지만 이것은 아닙니다. 기본적으로 의존하는 패키지가 vanilla js 이던 rollup 을 사용했던, webpack 을 사용했던 무관하게 최종 사용자가 잘 사용할 수 있어야 합니다. 웹팩 5로의 업그레이드 역시 patch 가 맞고, 여기서 발생한 실수를 고치는 것도 역시 patch 가 맞습니다.
