### ISSUE TITLE
네이버 클라우드 아이디 등록할 수 있게 해주세요

### ISSUE THREAD

**Issue by ViewDidLoad** [Shin-JaeHeon/vue-naver-maps#5]
클라우드 서비스 이용할 때 주소입니다.
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=YOUR_CLIENT_ID"></script>

현재 
Vue.use(naver, {
  ncpClientID: '등록된 아이디',
  useOpenAPI: true
})
변경해도 안되네요

**Comment by Shin-JaeHeon** [comment]
안녕하세요. 
클라우드 아이디를 사용하라면 useOpenAPI: true 부분을 삭제하셔야 합니다.
