### ISSUE TITLE
Vue.use 오류

### ISSUE THREAD

**Issue by devhun** [Shin-JaeHeon/vue-naver-maps#53]
Uncaught Error: Sorry, this plugin is only available in browsers at now. If you are using Nuxt.js, turn off ssr for this plugin.
 
개발자도구 콘솔에 위와 같은 오류가 발생하며 모듈 사용이 불가능합니다.

vue-cli 를 사용하여

vue create 로 프로젝트 생성하고 npm install vue-naver-maps 해서 생성한 새 프로젝트 입니다.

버전은 아래와 같습니다.
vue : ^2.6.14
vue-naver-maps : ^0.14.5

아래는 오류가 발생한 개발자도구 스크린샷 입니다.
<img width="1712" alt="스크린샷 2023-05-02 오전 8 30 51" src="https://user-images.githubusercontent.com/7991383/235548972-a3ddbf06-bbc3-4c6c-9ab6-7de6520e2971.png">

**Comment by jjangga0214** [comment]
#52 에서 해결될 겁니다~

**Comment by Shin-JaeHeon** [comment]
v0.14.6 버전을 배포하였으니 새로운 버전을 확인해주시면 감사하겠습니다.
