### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by Shin-JaeHeon** [Shin-JaeHeon/vue-naver-maps#8]
Support TypeScript

**Comment by Shin-JaeHeon** [comment]
TypeScript support for vue-naver-maps must wait for vue.js 3.0 to be released. Recently, I confirmed that vue-next was written in TypeScript.

**Comment by GauthierPLM** [comment]
@Shin-JaeHeon before VueJS 3.0 release, a good alternative is to provide a type definition of the component, even a light one, so IDE and TypeScript can work well with the component.

**Comment by Shin-JaeHeon** [comment]
I recently heard `vue.js 3.0` will be released in 20Q1. So, I wait for `vue.js 3.0`.
I don't want use many time for type definition, because it will be removed when vue.js 3.0 released.
 I'm sorry, but please wait until `vue.js 3.0` is released.

Thank you for watching this project.
